const DATABASE_NAME = '@comba'; 

const COLLECTION_USER = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENTS = `${DATABASE_NAME}:appointments`;

export {
    COLLECTION_USER,
    COLLECTION_APPOINTMENTS
}